import { defineConfig } from 'oxfmt';

export default defineConfig({
  trailingComma: 'all',
  bracketSameLine: false,
  singleQuote: true,
  arrowParens: 'avoid',
  ignorePatterns: [
    'patches/**',
    'android/**',
    'ios/**',
    'coverage/**',
    'pnpm-workspace.yaml',
    'pnpm-lock.yaml',
    'legacy',
    'turbo/generators/templates',
    'node_modules',
    '.pnp',
    '.pnp.js',
    'coverage',
    'cypress/videos',
    'cypress/screenshots',
    'cypress/downloads',
    '.next/',
    'out/',
    'build',
    '.DS_Store',
    '*.pem',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    '.pnpm-debug.log*',
    '.env',
    '.env.local',
    '.env.development.local',
    '.env.test.local',
    '.env.production.local',
    '.turbo',
    'dist',
    '.dist',
    'vscode',
    '.vscode',
    '.idea',
    '.map.ts',
  ],
  experimentalSortImports: {
    groups: [
      ['style'],
      ['builtin'],
      ['react', 'expo'],
      ['external'],
      ['roswell'],
      ['internal'],
      ['parent'],
      ['sibling'],
      ['index'],
      'unknown',
    ],
    customGroups: [
      {
        groupName: 'react',
        elementNamePattern: ['react', 'react/**'],
      },
      {
        groupName: 'expo',
        elementNamePattern: ['expo', 'expo/**'],
      },
      {
        groupName: 'roswell',
        elementNamePattern: ['@roswell/*', '@roswell/**'],
      },
    ],
  },
  experimentalTailwindcss: {
    attributes: ['class', 'className'],
    functions: ['clsx', 'cn'],
    preserveWhitespace: true,
  },
});
