allowBuilds:
  esbuild: false
  "@roswell/react-native-gdk": true
  "@shopify/react-native-skia": true
  "heroui-pro": true
  "@heroui-pro/react": true
  "heroui-native-pro": true
  "@zowe/secrets-for-zowe-sdk": false
  "@firebase/util": true
  protobufjs: false
  "@sentry/cli": false
  msgpackr-extract: false

overrides:
  axios: 1.15.2

nodeLinker: hoisted

minimumReleaseAgeExclude:
  - react-native-quick-crypto@1.1.5
  - babel-preset-expo@56.0.14
  - expo@56.0.8
  - expo-build-properties@56.0.16
  - expo-image-picker@56.0.15
  - expo-notifications@56.0.15
  - expo-task-manager@56.0.16
